import React from 'react';
import Head from 'next/head'
import { makeStyles } from '@material-ui/core/styles';
import CssBaseline from '@material-ui/core/CssBaseline';
import Container from '@material-ui/core/Container';
import Header from '@/modules/Header';
import Footer from '@/elements/Footer';

export default function Page(props) {
    const { title, children } = props;
    const sections = [
        { title: 'profile', url: '/profile' },
        { title: 'request', url: '/request' },
        { title: 'schedule', url: '/schedule' },
        { title: 'directory', url: '/directory' },
        { title: 'about', url: '/about' }
    ]

    return (
        <>
            <CssBaseline />
            <Head>
                <title>Radfx</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container maxWidth="lg">
                <Header title="RADFX" sections={sections} />
                <main> {children}</main>
            </Container>
            <Footer/>
        </>
    )
}